# THIS FILE IS GENERATED BY antigen-hs!!!!

source /home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-functional/functional.plugin.zsh
source /home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-bd/bd.plugin.zsh
source /home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source /home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search/zsh-history-substring-search.plugin.zsh
source /home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-sindresorhus-SLASH-pure/pure.plugin.zsh
fpath+=/home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-functional
fpath+=/home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-bd
fpath+=/home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting
fpath+=/home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-history-substring-search
fpath+=/home/seanstrom/.antigen-hs/repos/https-COLON--SLASH--SLASH-github.com-SLASH-sindresorhus-SLASH-pure
